config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning.urls')),
    path('accounts/',include('allauth.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
]

learning/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'learning'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('question/',views.QuestionView.as_view(),name="question"),
    path('question_confirm/',views.Question_confirmView.as_view(),name='question_confirm'),
    path('question_done/',views.Question_doneView.as_view(),name="question_done"),
    path('block', views.BlockView.as_view(), name='block'),
    path('enzan', views.EnzanView.as_view(), name='enzan'),
    path('question2', views.Question2View.as_view(), name='question2'),
    path('question3', views.Question3View.as_view(), name='question3'),
    path('question4', views.Question4View.as_view(), name='question4'),
    path('question5', views.Question5View.as_view(), name='question5'),
    path('question6', views.Question6View.as_view(), name='question6'),
    path('question7', views.Question7View.as_view(), name='question7'),
    path('question8', views.Question8View.as_view(), name='question8'),
    path('question9', views.Question9View.as_view(), name='question9'),
    path('question10', views.Question10View.as_view(), name='question10'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    # 拡張ユーザモデル

    class Meta:
        verbose_name_plural = 'CustomUser'

learning/models.py
from typing import Tuple
from django.db import models


class learning(models.Model):

    class Meta:
        verbose_name_plural = 'learning'

    def __str__(self):
        return self.message

learning/forms.py
from django import forms
from django.core.mail import EmailMessage
from django.forms import fields
from .models import learning

class QuestionForm(forms.Form):
    message  = forms.CharField(label='興味を持ったことは？', widget=forms.Textarea)
    message1 = forms.CharField(label='今回の講義の改善点は？', widget=forms.Textarea)
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
       

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

        self.fields['message1'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message1'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'
       
    def send_email(self):

        message1 = self.cleaned_data['message']+self.cleaned_data['message1']

        from_email = 'admin@example.com'
        recipient_list = ["admin@example.com"]

        message = EmailMessage("hoge", message1, from_email, recipient_list)
        message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

learning/views.py
import logging
from django.contrib import messages
from django.contrib.messages.api import success
from django.db import models
from django.urls import reverse_lazy
from django.core.mail import message
from django.http import request
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect


class IndexView(generic.TemplateView):
    template_name = "index.html"
class BlockView(generic.TemplateView):
    template_name = "public/block.html"
class EnzanView(generic.TemplateView):
    template_name = "public/learning_shisoku.html"
class Question2View(generic.TemplateView):
    template_name = "public/question2.html"
class Question3View(generic.TemplateView):
    template_name = "public/question3.html"
class Question4View(generic.TemplateView):
    template_name = "public/question4.html"
class Question5View(generic.TemplateView):
    template_name = "public/question5.html"
class Question6View(generic.TemplateView):
    template_name = "public/question6.html"
class Question7View(generic.TemplateView):
    template_name = "public/question7.html"
class Question8View(generic.TemplateView):
    template_name = "public/question8.html"
class Question9View(generic.TemplateView):
    template_name = "public/question9.html"
class Question10View(generic.TemplateView):
    template_name = "public/question10.html"

from .forms import QuestionForm #, learningCreateForm


logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'index.html')

class IndexView(generic.TemplateView):
    template_name = "index.html"

class QuestionView(generic.FormView):
    template_name = "question.html"
    form_class = QuestionForm
    success_url = reverse_lazy('learning:question_done')
     
    def form_valid(self, form):
        form.send_email()
        logger.info('Question sent by {}'.format(form.cleaned_data['message']))
        logger.info('Question sent by {}'.format(form.cleaned_data['message1']))
        return super().form_valid(form)

class Question_doneView(generic.FormView):
    template_name = "question_done.html"
    form_class = QuestionForm
    success_url = reverse_lazy('learning:question_done')

class Question_confirmView(generic.FormView):
    template_name = "question_confirm.html"
    form_class = QuestionForm
    success_url = reverse_lazy('learning:question_done')

def LoginView(request):
    return HttpResponseRedirect('social:begin', kwargs=dict(backend='google-oauth2'))

learning/templates/base.html
{% load md5url %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /> -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet"
        type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    {% block head %}{% endblock %}
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Clarence Taylor</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'learning:index' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'learning:enzan' %}">四則演算</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'learning:block' %}">問題ページ</a></li>


                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'learning:question' %}">アンケート</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account_login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account_signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block header %}{% endblock %}

    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    {% block content %}{% endblock %}
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>

</html>

learning/templates/index.html
{% extends 'base.html' %}
{% load md5url %}
{% load static %}

{% block titile %}入学促進学習サイト{% endblock %}
{% block content %}
<!-- Page Content-->
<style>
    h1{
        font-size: 11.93vw;
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        width: 8em
    }
</style>
<div class="container-fluid p-0">
    <!-- About-->
    <section class="resume-section" id="about">
        <!-- <div class="resume-section-content"> -->
            <h1 class="mb-0">
                O-learning
                <!-- <span class="text-primary">学習サイト</span> -->

            </h1>
            <style>
                
            </style>
        <!-- </div> -->
    </section>
</div>
{% endblock %}

learning/templates/question.html
{% extends 'base.html' %}

{% block title %}アンケート{% endblock %}

{% block active_question %}active{%endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">

                <style>
                    a {
                        text-align: center;
                    }
                </style>
                <a>
                    <style>
                        .check {
                            margin-left: 30px;
                        }
                    </style>
                    <div class="chk">
                        <div class="no">
                            <h3>今回の講義の評価はどうでしたか? </h3><br>
                            <input class="check" type="radio" name="check" value="1">1
                            <input class="check" type="radio" name="check" value="2">2
                            <input class="check" type="radio" name="check" value="3">3
                            <input class="check" type="radio" name="check" value="4">4
                            <input class="check" type="radio" name="check" value="5">5
                            <br>
                            <br>
                        </div>
                    </div>
                </a>
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}

                <div class="form-group row">
                    <label for="{{ field.id_for_label}}" class="col-sm-4 col-form-label">
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">

                        {{ field }}
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}
                <br>
                <style>
                    button {
                        margin-right: 37%;
                    }
                </style>
                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit" onclick="history.back()">戻る</button>
                    <button class="btn btn-primary" type="submit">確認</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

learning/templates/question_done.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>アンケート送信画面</title>
</head>
<style>
    body {
        text-align: center;
    }
</style>

<body>

    <h1>この内容でいいですか？</h1>
    {{form}}
</body>
<a href="/"><button>送信</button></a>
<button onclick="history.back()">戻る</button>

</html>